---
name: tests

on: [push, pull_request]

jobs:
  tests:
    name: Run Tests (Elixir ${{ matrix.combo.elixir }} - OTP ${{ matrix.combo.otp }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        combo:
          - elixir: '1.15'
            otp: '24'
          - elixir: '1.19.5'
            otp: '28.4'
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.combo.otp }}
          elixir-version: ${{ matrix.combo.elixir }}
      - uses: actions/cache@v4
        with:
         path: deps
         key: ${{ runner.os }}-${{ matrix.combo.otp }}-${{ matrix.combo.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
         restore-keys: |
           ${{ runner.os }}-${{ matrix.combo.otp }}-${{ matrix.combo.elixir }}-
      - run: mix deps.get
      - run: mix format --dry-run --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test --trace
      - run: mix coveralls.github
        if: matrix.combo.elixir == '1.19.5'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
